version: '3.7'

services:

  db:
    image: mysql:latest
    volumes:
      - ./sqldata3:/var/lib/mysql
    networks:
      - intranet
    restart: on-failure
    environment:
      MYSQL_USER: tung
      MYSQL_PASSWORD: tung123
      MYSQL_ROOT_PASSWORD: sieunhantung96
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_HOST: gocrud
    ports:
      - 3306:3306

  gocrud:
    depends_on:
      - db
    networks:
      - intranet
    image: alpine:latest
    volumes:
      - ./app.env:/app.env
      - ./goCRUD:/goCRUD
    restart: on-failure
    command: /goCRUD
    ports:
      - 1207:1207

  caddy:
    networks:
      - intranet
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - 1277:1277
    volumes:
      - ./caddy:/etc/caddy
      - ./root:/usr/share/caddy

networks:
  intranet: null
